sudo: required
services:
  - docker
language: node_js
node_js:
  - stable
env:
  - DAVE_VERSION=0.1.1
install:
  - npm install -g dave@"$DAVE_VERSION"
before_script:
  - dave build
script:
  - dave test
after_success:
  - docker login -u aa8y -p "$DOCKER_PASSWORD"
  - dave push
ignore:
  - "*.md"
